FROM mcr.microsoft.com/devcontainers/python:0-3.11

# Install the apt package
#RUN apt-get update && apt-get install nano

# Install pip package
RUN pip install -U pip && pip install --no-cache-dir \
    numpy \
    pandas \
    scipy \
    scikit-learn \
    torch \
    torchvision \
    plotly

ENV TORCH '2.0.1+cu117'
RUN pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html && \
    pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html && \
    pip install -q torch-cluster -f https://data.pyg.org/whl/torch-${TORCH}.html && \
    pip install -q git+https://github.com/pyg-team/pytorch_geometric.git