FROM mcr.microsoft.com/devcontainers/python:0-3.11

# Install the apt package
RUN apt-get update && apt-get install -y \
    nano \
    emacs \
    tmux 

# Install pip package
RUN pip install -U pip && pip install --no-cache-dir \
    ipykernel \
    numpy \
    pandas \
    scipy \
    scikit-learn \
    seaborn \
    plotly
